### ISSUE TITLE
WASM compilation

### ISSUE THREAD

**Issue by carloslfu** [1p6/supercop.js#3]
Sice WebAssembly is compatible and stable on most browsers and Node.js 8+, would be nice to have it in the project. This could be done by setting the Emscripten WASM flag in the compile command

**Comment by 1p6** [comment]
A better, working version was made by @nazar-pc using WASM, I'd recommend checking it out.
I added a link to it in this commit: https://github.com/1p6/supercop.js/commit/f19dd42e509676ec530e7f12daf2bd9dd9b50da8
